---
- name: IaC for Laptop 'PRECISION'
  hosts: all
  vars:
    main_username: simon
  become: true
  tasks:
    - name: Set up new user
      ansible.builtin.import_tasks:
        file: tasks/common/set_up_main_account.yml

    - name: Set up zsh
      ansible.builtin.import_tasks:
        file: tasks/common/set_up_zsh.yml

    - name: Install packages
      ansible.builtin.import_tasks:
        file: tasks/common/install_packages.yml

    - name: Set up bare backup
      ansible.builtin.import_tasks:
        file: tasks/common/set_up_bare_backup.yml 
      vars:
        type: master
        ssh:  