- name: Go through all the files in assets/docker_composes/*
  block:
  - name: Make sure directory exists
    ansible.builtin.file:
      path: /opt/{{ item }}
      state: directory
      owner: {{ main_username }}
      group: {{ main_username }}
      mode: '0755'

  - name: copy Docker Compose files
    copy:
      src: assets/docker_composes/{{ item }}
      dest: opt/{{ item }}/docker-compose.yml

  - name: deploy Docker Compose stack
    community.docker.docker_compose:
      project_src: /opt/{{ item }}
      files:
      - docker-compose.yml
      - docker-compose.prod.yml
  tag: homeAssistant
  loop:
  - homeAssistant
