- name: Go through all the files in assets/docker_composes
  block:
    - name: Make sure directory exists
      ansible.builtin.file:
        path: /opt/{{ item }}
        state: directory
        owner: "{{ main_username }}"
        group: "{{ main_username }}"
        mode: '0755'
      with_items:
        - "{{ files }}"

    - name: Copy Docker Compose files
      ansible.builtin.copy:
        src: assets/docker_composes/{{ item }}
        dest: /opt/{{ item }}/docker-compose.yml
        owner: "{{ main_username }}"
        group: "{{ main_username }}"
        mode: '0644'
        force: true
      with_items:
        - "{{ files }}"
      register: output

    - name: Remove containers
      ansible.builtin.command: docker-compose rm -f
      args:
        chdir: /opt/{{ item }}
      with_items:
        - "{{ files }}"

    - name: Run Docker Compose
      ansible.builtin.command: docker-compose up -d
      args:
        chdir: /opt/{{ item }}
      with_items:
        - "{{ files }}"