---
- name: "Add new sudo user {{ MAIN_USERNAME }}"
  ansible.builtin.user:
    name: "{{ MAIN_USERNAME }}"
    state: present
    groups: sudo,adm,systemd-journal
    append: true

- name: "Add new sudo user {{ MAIN_USERNAME }} to sudoers"
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "{{ MAIN_USERNAME }} ALL=(ALL) NOPASSWD:ALL"
    state: present
    validate: 'visudo -cf %s'

- name: Copy authorized_keys
  block:
    - name: Create .ssh directory
      ansible.builtin.file:
        path: "/home/{{ MAIN_USERNAME }}/.ssh"
        state: directory
        owner: "{{ MAIN_USERNAME }}"
        group: "{{ MAIN_USERNAME }}"
        mode: 0700
        remote_src: yes

    - name: Copy authorized_keys
      ansible.builtin.copy:
        src: "{{ lookup('file', '~/.ssh/authorized_keys') }}"
        dest: "/home/{{ MAIN_USERNAME }}/.ssh/authorized_keys"
        owner: "{{ MAIN_USERNAME }}"
        group: "{{ MAIN_USERNAME }}"
        mode: 0600
        when: lookup('file', '~/.ssh/authorized_keys') is not none
        remote_src: yes

- name: Disable password login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
    validate: 'sshd -t -f %s'