---
- name: Install zsh
  ansible.builtin.package:
    name: zsh
    state: present

- name: Change default shell to zsh
  ansible.builtin.user:
    name: "{{ MAIN_USERNAME }}"
    shell: /usr/bin/zsh
