- name: "Add new sudo user {{ main_username }}"
  ansible.builtin.user:
    name: "{{ main_username }}"
    state: present
    groups: sudo,adm,systemd-journal
    append: true

- name: "Add new sudo user to sudoers"
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "{{ main_username }} ALL=(ALL) NOPASSWD:ALL"
    state: present
    validate: 'visudo -cf %s'

- name: Copy authorized_keys
  block:
    - name: Create .ssh directory
      ansible.builtin.file:
        path: "/home/{{ main_username }}/.ssh"
        state: directory
        owner: "{{ main_username }}"
        group: "{{ main_username }}"
        mode: '0700'

    - name: Copy authorized_keys
      ansible.posix.authorized_key:
        user: "{{ main_username }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/authorized_keys') }}"
      ignore_errors: true

- name: Disable password login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
    validate: 'sshd -t -f %s'

- name: Remove user
  ansible.builtin.user:
    user: name={{ USER }}
    state: absent
  become: true
  become_method: sudo
  when: USER is defined and USER != main_username and USER != 'root'
