version: "3"
services:
    cups:
        image: anujdatar/cups
        container_name: cups
        restart: unless-stopped
        ports:
            - "631:631"
        devices:
            - /dev/bus/usb:/dev/bus/usb
        environment:
            - CUPSADMIN=${CUPSADMIN}
            - CUPSPASSWORD=${CUPSPASSWORD}
            - TZ="Europe/Amsterdam"
        volumes:
            - ./config:/etc/cups